### ISSUE TITLE
SysAp did not respond in time

### ISSUE THREAD

**Issue by PaTri16** [henry-spanka/homebridge-freeathome#58]
Hi,

I have a problem.

[26.12.21, 10:49] [free@home] SysAp did not respond in time: 0000/odp0006/
[26.12.21, 10:49] [free@home] If this issue persists please try to login as the API user in the free@home UI. The SysAp might disable websocket notifications if the connection is idle for too long.
[26.12.21, 10:49] [free@home] See: https://github.com/henry-spanka/homebridge-freeathome#tips--tricks

The tip to log into SysAp doesn‘t work. SysAp ist on Version 3.0.0 

Need help!

**Comment by obituz** [comment]
I have the same problem, but with version 2.6.4.
The update is correctly applied (temperature is changed), but the UI keeps the old state due to this timeout. Any hints?
Firmware update, Restarts, Logins as suggested... No change.

**Comment by rubenvanderzwan80** [comment]
Same goes for me, logging in and out does not help unfortunately. Or do you mean to login in and out from the device actually running HomeBridge?

**Comment by Alex2612** [comment]
Same issue here. Also logged in to the SysAP with the "Homebridge-User"...without any result. Everything is up to date. Plugin version 2.0.3, SysAP Firmware 3.0.0

Also tried do set up free@home via "Sub-Bridge"...still nothing.

Interesting: After restarting Homebridge, I´m allowed to toggle exactly 1 Switch. The Lamp for example is being turned, but the state in the Home-App won´t even change. Afert that...nothing but the same error again:
[04/01/2022, 20:12:57] [homebridge-freeathome] SysAp did not respond in time: 0003/odp0000/1
[04/01/2022, 20:12:57] [homebridge-freeathome] If this issue persists please try to login as the API user in the free@home UI. The SysAp might disable websocket notifications if the connection is idle for too long.

**Comment by Rjlmason** [comment]
I also have this same issue, logging in does not help nor resolve this issue. Is there a fix in the works to resolve this?

**Comment by henry-spanka** [comment]
Hi there. I am still running Firmware 2.X so there might be an issue with the new firmware however we should fix it with the new REST API that should be integrated into the next release.

Specifically you need to login to the SysAp via the **webpanel** and turn on/off a lamp. After that restart homebridge and (hopefully) it should work again.

**Comment by Blandwehr** [comment]
I also have this same issue, SW 2.64... Workaround for me: restart SysAp and after this, restart homebridge. Than I received loging messages like "Received log data which is currently not supported" I think that helps to leave the connection open ?!?

**Comment by henry-spanka** [comment]
You can turn off log data in the SysAp Settings. It has nothing to do which the mentioned issue. We currently do not use this that hence you are receiving that message.

**Comment by reddeadhand** [comment]
Hi @henry-spanka ,
also for me the issue still persists with v3.0. Are there any plans when the issue will be fixed for that version?

**Comment by henry-spanka** [comment]
Hi @reddeadhand,
I will release a new version by the end of the week that both supports older clients (2.X) and > 3.0

**Comment by henry-spanka** [comment]
I have released a new version. Please update home bridge and it should work.
